redis-dev:
  image: redis
  ports:
    - "6379:6379"
elasticsearch-dev:
  image: elasticsearch:1.7
  ports:
    - "9200:9200"
    - "9300:9300"
kibana-dev:
  image: kibana:4.1
  ports:
    - "5601:5601"
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch-dev:9200
  links:
    - elasticsearch-dev

