STIX project data structures converted to Prismatic schemas

* How to convert a STIX specification to one of our schemas:

** Update the data_structures.md document for any schema changes!

** Value practical and concrete over extensible and abstract

** Flatten and simplify when possible

  Especially when a STIX field contains a data structre that is a
  wrapper around a defined vocabulary without adding important fields
  in the wrapping data structure.  In that case, avoid the wapper and
  use an enum for the vocabulary.

** Record any omitted fields in comments at the bottom of each structure.

** Note which fields are added by us (not part of STIX).

** Prefer references over nested data structures.

  Use named references so that we can tell what the reference points at.

** References should point to stored object types.

** Use capital letters in identifiers and keywords for acronyms.

** Fields should be renamed to their acronyms when we implement the referenced structure.

** Each stored structure should have a NewStructure and StoredStructure schema to match

** Rename fields to shorten smurfy names (eg threat_actor -> actor)

** Rename some other fields, listed below

***  information_source -> source
