version: '2'
services:

  elasticsearch5:
    build: ./m1-images/elasticsearch5

  docker-riemann-dev:
    build:
      context: ./m1-images/riemann
      args:
        - RIEMANN_VERSION=0.3.5

  docker-riemann-dash-dev:
    build: ./m1-images/riemann-dash
