version: '2'
services:
  elasticsearch7:
    image: elasticsearch:7.17.0
    environment:
      - cluster.name=elasticsearch7
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      #- xpack.security.authc.anonymous.roles=superuser # allows no auth for test purpose
      - ELASTIC_PASSWORD=ductile
    ports:
      - "9207:9200"
      - "9307:9300"
